services:
  podnik_db:
    container_name: podnik_db
    image: postgres:17-alpine
    volumes:
      - podnik_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - podnik_network

  podnik_app:
    container_name: podnik_app
    build: .
    entrypoint: /script/entrypoint.sh
    volumes:
      - ./app:/app
      - ./conf:/conf
      - ./script:/script
    depends_on:
      - podnik_db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONWARNINGS=ignore::UserWarning
    env_file:
      - .env
    networks:
      - podnik_network

  podnik_nginx:
    image: nginx:mainline-alpine
    container_name: podnik_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - podnik_app
    networks:
      - podnik_network

networks:
  podnik_network:

volumes:
  podnik_postgres_data:

